-- REVIEW ONLY — additive schema preparation for the local Hikvision sync.
-- Do not execute automatically.
-- No attendance rows, workers, teams, mappings, or existing policies are modified.

alter table public.attendance
  add column if not exists attendance_source text not null default 'manual',
  add column if not exists manual_override boolean not null default false,
  add column if not exists biometric_sync_key text,
  add column if not exists biometric_sync_metadata jsonb,
  add column if not exists attendance_day_fraction numeric(3,1);

-- Existing rows deliberately remain protected as manual records by the default source.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.attendance'::regclass
      and conname = 'attendance_source_valid'
  ) then
    alter table public.attendance
      add constraint attendance_source_valid
      check (attendance_source in ('manual', 'biometric'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.attendance'::regclass
      and conname = 'attendance_day_fraction_valid'
  ) then
    alter table public.attendance
      add constraint attendance_day_fraction_valid
      check (attendance_day_fraction is null or attendance_day_fraction in (0, 0.5, 1));
  end if;
end
$$;

create unique index if not exists attendance_biometric_sync_key_unique
  on public.attendance (biometric_sync_key)
  where biometric_sync_key is not null;

comment on column public.attendance.attendance_source is
  'manual records are never overwritten by the local biometric sync; biometric records are sync-managed.';
comment on column public.attendance.manual_override is
  'when true, prevents future biometric sync updates to that attendance row.';
comment on column public.attendance.biometric_sync_key is
  'idempotency key for a single worker and work date generated by the local Hikvision sync.';
