-- REVIEW ONLY — definitive additive preparation for biometric attendance workflow.
-- Do not execute automatically.
-- This migration does not delete data and does not alter workers, teams, mappings, or policies.
-- It supersedes attendance_biometric_sync_upgrade.sql when neither migration has been executed.

alter table public.attendance
  add column if not exists attendance_source text not null default 'manual',
  add column if not exists manual_override boolean not null default false,
  add column if not exists biometric_sync_key text,
  add column if not exists biometric_sync_metadata jsonb,
  add column if not exists attendance_day_fraction numeric(3,1);

-- This is the only existing constraint intentionally replaced. It expands the
-- approved status vocabulary while preserving all existing status values.
alter table public.attendance
  drop constraint if exists attendance_status_check;

alter table public.attendance
  add constraint attendance_status_check
  check (status in ('pending', 'in_progress', 'present', 'late', 'half_day', 'absent'));

-- Deterministic compatibility layer for existing clients that only send status.
-- It runs before the day-fraction CHECK constraint is evaluated and overrides
-- any inconsistent fraction supplied by a client.
create or replace function public.set_attendance_day_fraction_from_status()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.attendance_day_fraction := case new.status
    when 'present' then 1.0
    when 'late' then case when new.check_out is null then 0.5 else 1.0 end
    when 'half_day' then 0.5
    when 'absent' then 0
    when 'pending' then null
    when 'in_progress' then null
    else null
  end;
  return new;
end;
$$;

drop trigger if exists attendance_set_day_fraction_from_status on public.attendance;
create trigger attendance_set_day_fraction_from_status
before insert or update of status, check_in, check_out on public.attendance
for each row
execute function public.set_attendance_day_fraction_from_status();

-- Existing present/absent rows receive only the new, deterministic day-fraction
-- value. Their status, timestamps, notes, worker, and date are not changed.
update public.attendance
set attendance_day_fraction = case
  when status = 'present' then 1.0
  when status = 'absent' then 0
  else attendance_day_fraction
end
where attendance_day_fraction is null
  and status in ('present', 'absent');

-- Existing absent/check-out constraints are deliberately retained unchanged:
--   attendance_absent_has_no_times
--   attendance_checkout_after_checkin
--   attendance_worker_date_unique

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.attendance'::regclass
      and conname = 'attendance_source_valid'
  ) then
    alter table public.attendance
      add constraint attendance_source_valid
      check (attendance_source in ('manual', 'biometric'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.attendance'::regclass
      and conname = 'attendance_day_fraction_by_status_valid'
  ) then
    alter table public.attendance
      add constraint attendance_day_fraction_by_status_valid
      check (
        (status = 'present' and attendance_day_fraction = 1.0)
        or (
          status = 'late'
          and check_in is not null
          and (
            (check_out is null and attendance_day_fraction = 0.5)
            or (check_out is not null and attendance_day_fraction = 1.0)
          )
        )
        or (status = 'half_day' and attendance_day_fraction = 0.5)
        or (status = 'absent' and attendance_day_fraction = 0)
        or (status in ('pending', 'in_progress') and attendance_day_fraction is null)
      );
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.attendance'::regclass
      and conname = 'attendance_workflow_times_valid'
  ) then
    alter table public.attendance
      add constraint attendance_workflow_times_valid
      check (
        (status = 'pending' and check_in is null and check_out is null)
        or (status = 'in_progress' and check_in is not null and check_out is null)
        or (status = 'half_day' and check_in is not null and check_out is null)
        or (status = 'late' and check_in is not null)
        or status in ('present', 'absent')
      );
  end if;
end
$$;

create unique index if not exists attendance_biometric_sync_key_unique
  on public.attendance (biometric_sync_key)
  where biometric_sync_key is not null;

comment on column public.attendance.attendance_source is
  'manual records are never overwritten by the local biometric sync; biometric records are sync-managed.';
comment on column public.attendance.manual_override is
  'when true, prevents future biometric sync updates to that attendance row.';
comment on column public.attendance.biometric_sync_key is
  'idempotency key for a single worker and work date generated by the local Hikvision sync.';
