import { useEffect, useMemo, useState } from 'react'
import { getWorkersRequest, getWorkersActivatedTodayRequest } from '../api/workersApi'
import { getAttendanceRequest } from '../api/attendanceApi'
import { getInactiveWorkerBiometricActivityRequest } from '../api/biometricMappingApi'
import { buildWorkerControlAlerts } from '../utils/workerControlCenter'
import Modal from '../components/Modal/Modal'

const today = () => new Date().toLocaleDateString('en-CA', { timeZone: 'Africa/Kinshasa' })
const monthStart = (d) => `${d.slice(0, 7)}-01`
const monday = (d) => { const x = new Date(`${d}T12:00:00`); x.setDate(x.getDate() - ((x.getDay() + 6) % 7)); return x.toISOString().slice(0, 10) }
const text = { overview: 'نظرة عامة اليوم', absent: 'الغائبون اليوم', consecutive: 'الغياب المتتالي' }

function ReportSection({ id, title, rows, columns, onDetails }) {
  return <section id={id} className="mb-14 scroll-mt-6"><div className="mb-4 flex items-center justify-between border-b-2 border-(--border) pb-3"><h3 className="text-2xl font-extrabold">{title}</h3><span className="status-badge status-badge--neutral">{rows.length}</span></div><div className="overflow-x-auto rounded-xl border border-(--border) bg-white"><table className="min-w-full text-base"><thead className="bg-(--surface-subtle)"><tr>{columns.map(c => <th className="whitespace-nowrap px-5 py-4 text-start font-extrabold" key={c.label}>{c.label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr className="border-t border-(--border)" key={`${row.type}-${row.worker?.id}-${index}`}>{columns.map(c => <td className="whitespace-nowrap px-5 py-4" key={c.label}>{c.render(row)}</td>)}</tr>)}</tbody></table>{!rows.length ? <p className="p-7 text-(--muted)">لا توجد حالات حالياً</p> : null}</div></section>
}

export default function WorkerControlCenter() {
  const [date] = useState(today()); const [state, setState] = useState({ workers: [], attendance: [], events: [], activated: [] }); const [selected, setSelected] = useState(null)
  useEffect(() => { Promise.all([getWorkersRequest(), getAttendanceRequest({ date_from: monthStart(date), date_to: date, paginate: true }), getInactiveWorkerBiometricActivityRequest({ attendanceDate: date }), getWorkersActivatedTodayRequest()]).then(([w, a, e, x]) => setState({ workers: w.data || [], attendance: a.data || [], events: e.data || [], activated: x.data || [] })) }, [date])
  const alerts = useMemo(() => buildWorkerControlAlerts({ ...state, today: date, weekStart: monday(date), monthStart: monthStart(date) }), [state, date])
  const oneEach = (rows) => rows.filter((row, index, all) => all.findIndex(item => item.worker?.id === row.worker?.id) === index)
  const absent = oneEach(alerts.filter(a => a.todayRow?.status === 'absent'))
  const consecutive = [...alerts.filter(a => a.type === 'consecutive_absence')].sort((a, b) => (b.longest || 0) - (a.longest || 0))
  const groups = [{ id: 'absent-today', label: 'الغائبون اليوم', rows: absent }, { id: 'consecutive-absence', label: 'الغياب المتتالي', rows: consecutive }, { id: 'weekly-absence', label: 'الغياب الأسبوعي', rows: alerts.filter(a => a.type === 'weekly_absence') }, { id: 'monthly-monitoring', label: 'المراقبة الشهرية', rows: alerts.filter(a => a.type === 'monthly_absence') }, { id: 'inactive-punch', label: 'غير مفعّلين قاموا بالبصمة', rows: alerts.filter(a => a.type === 'inactive_punch') }, { id: 'activated-today', label: 'تم تفعيلهم اليوم', rows: alerts.filter(a => a.type === 'activated_today') }, { id: 'returned-after-absence', label: 'عادوا بعد غياب', rows: alerts.filter(a => a.type === 'returned_after_absence') }]
  const worker = { label: 'العامل', render: r => <><b>{r.worker?.full_name || '—'}</b></> }; const team = { label: 'الفريق', render: r => r.worker?.team_name || '—' }; const details = { label: 'التفاصيل', render: r => <button className="btn-secondary px-3 py-1" onClick={() => setSelected(r)}>Details</button> }
  const weekly = [...alerts.filter(a => a.type === 'weekly_absence')].sort((a,b) => (b.weekAbsent||0)-(a.weekAbsent||0) || (b.longest||0)-(a.longest||0))
  const monthly = alerts.filter(a => a.type === 'monthly_absence')
  return <section className="w-full pb-12" dir="rtl"><div className="mb-9"><h2 className="text-3xl font-extrabold">مركز مراقبة العمال</h2><p className="mt-2 text-base text-(--muted)">متابعة تشغيلية مبنية على بيانات الحضور الحالية.</p></div><section id="today-overview" className="mb-14"><h3 className="mb-5 text-2xl font-extrabold">{text.overview}</h3><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{groups.map(g => <button key={g.id} className="surface-card min-h-34 p-5 text-start" onClick={() => document.getElementById(g.id)?.scrollIntoView({ behavior: 'smooth' })}><p className="text-base font-bold text-(--muted)">{g.label}</p><b className="mt-3 block text-4xl">{g.rows.length}</b></button>)}</div></section><ReportSection id="absent-today" title={text.absent} rows={absent} columns={[worker,{label:'كود الموظف',render:r=>r.worker?.employee_code||'—'},team,{label:'الغياب المتتالي',render:r=>r.longest||0},{label:'غياب الأسبوع',render:r=>r.weekAbsent||0},{label:'غياب الشهر',render:r=>r.monthAbsent||0},{label:'آخر حضور',render:r=>r.lastAttendance?.attendance_date||'—'},details]} /><ReportSection id="consecutive-absence" title={text.consecutive} rows={consecutive} columns={[worker,team,{label:'الأيام المتتالية',render:r=>r.longest||0},{label:'الخطورة',render:r=>r.severity},{label:'غياب الأسبوع',render:r=>r.weekAbsent||0},{label:'غياب الشهر',render:r=>r.monthAbsent||0},details]} /><ReportSection id="weekly-absence" title="مراقبة الغياب الأسبوعي" rows={weekly} columns={[worker,{label:'كود الموظف',render:r=>r.worker?.employee_code||'—'},team,{label:'غياب الأسبوع',render:r=>r.weekAbsent||0},{label:'الغياب المتتالي',render:r=>r.longest||0},{label:'غياب الشهر',render:r=>r.monthAbsent||0},{label:'الخطورة',render:r=>r.severity},details]} /><ReportSection id="monthly-monitoring" title="المراقبة الشهرية" rows={monthly} columns={[worker,{label:'كود الموظف',render:r=>r.worker?.employee_code||'—'},team,{label:'غياب الشهر',render:r=>r.monthAbsent||0},{label:'نصف يوم',render:r=>r.half||0},{label:'الغياب المتتالي',render:r=>r.longest||0},{label:'آخر حضور',render:r=>r.lastAttendance?.attendance_date||'—'},{label:'المتابعة',render:r=>r.severity},details]} /><Modal isOpen={!!selected} title={selected?.worker?.full_name || ''} onClose={() => setSelected(null)}><p>Team: {selected?.worker?.team_name || '—'}</p><p>Status: {selected?.worker?.is_active ? 'Active' : 'Inactive'}</p><p>Operational start: {selected?.worker?.operational_start_date || '—'}</p><p>Today: {selected?.todayRow?.status || '—'}</p></Modal></section>
}
