import { useEffect, useMemo, useState } from 'react'
import { getErrorMessage } from '../../api/axios'
import { saveAttendanceManuallyRequest } from '../../api/attendanceApi'
import { createPayrollAdjustmentRequest, getPayrollOperationsDataRequest, persistPayrollDraftRequest, setWeeklyPayrollRunStatusRequest } from '../../api/payrollOperationsApi'
import { saveWorkerPayrollSettingsRequest } from '../../api/payrollSettingsApi'
import { applyPayrollAdjustments, attachSundayEntitlements, calculatePayrollLine, datesForRange, monthlyCycle, monthlyDailyValue, totalLines } from '../../utils/payrollCalculations'
import { exportPayrollExcel, printPayrollReport } from '../../utils/payrollExports'
import { formatPayrollMoney } from '../../utils/payrollCurrency'
import { useTranslation } from '../../i18n/LanguageContext'
import Modal from '../Modal/Modal'
import Table from '../Table/Table'

const statusLabel = (value, t) => ({ draft: t('payroll.statusDraft'), reviewed: t('payroll.statusReviewed'), finalized: t('payroll.statusFinalized'), paid: t('payroll.statusPaid') }[value] || value)
const isSunday = (date) => new Date(`${date}T12:00:00`).getDay() === 0
const latestTermForType = (line, paymentType) => (line?.worker?.payroll_compensation_terms || [])
  .filter((term) => term.payment_type === paymentType)
  .sort((left, right) => String(right.effective_from).localeCompare(String(left.effective_from)))[0] || null

const makeLines = (data) => {
  const attendance = new Map((data?.attendance || []).map((row) => [`${row.worker_id}|${row.attendance_date}`, row]))
  const holidays = new Set((data?.holidays || []).map((holiday) => holiday.holiday_date))
  return (data?.workers || []).filter((worker) => worker.is_active !== false && worker.payment_type === 'monthly').map((worker) => {
    const term = worker.payroll_compensation
    const cycle = monthlyCycle(term?.monthly_payroll_cycle_start_date)
    if (!cycle || term?.monthly_salary == null || !term?.currency_code) return null
    const run = (data?.runs || []).find((item) => item.payment_type === 'monthly' && item.scheduled_payment_date === cycle.due)
    return attachSundayEntitlements({ ...calculatePayrollLine({ worker, term, attendanceByDate: attendance, dates: datesForRange(cycle.start, cycle.end), rules: data?.rules, holidayDates: holidays, paymentType: 'monthly' }), cycle }, data?.sundayPayments, cycle.due)
  }).filter(Boolean)
}

function MonthlyEditPanel({ line, draft, saving, onClose, onSave }) {
  const { t } = useTranslation()
  const [values, setValues] = useState({})
  useEffect(() => {
    const term = line?.term || {}
    setValues({ paymentType: line?.worker?.payment_type || 'monthly', currency: term.currency_code || line?.currency || '', dailyRate: term.daily_rate ?? '', salary: term.monthly_salary ?? line?.monthlySalary ?? '', transport: term.daily_transport_allowance ?? 0, overtimeRate: term.overtime_rate_per_hour ?? '', overtimeStart: term.overtime_start_time || '', cycleStart: term.monthly_payroll_cycle_start_date || '', effectiveFrom: new Date().toISOString().slice(0, 10), type: 'bonus', amount: '', reason: '', attendance: Object.fromEntries((line?.details || []).map((detail) => [detail.date, { status: detail.status, check_in: detail.row?.check_in || '', check_out: detail.row?.check_out || '' }])) })
  }, [line])
  if (!line) return null
  const update = (name, value) => setValues((current) => ({ ...current, [name]: value }))
  const updateAttendance = (date, name, value) => setValues((current) => ({ ...current, attendance: { ...current.attendance, [date]: { ...current.attendance?.[date], [name]: value } } }))
  const selectPaymentType = (paymentType) => {
    const savedTerm = latestTermForType(line, paymentType)
    setValues((current) => ({ ...current, paymentType, dailyRate: paymentType === 'weekly' ? savedTerm?.daily_rate ?? '' : '', salary: paymentType === 'monthly' ? savedTerm?.monthly_salary ?? line?.worker?.monthly_salary ?? '' : '', cycleStart: paymentType === 'monthly' ? savedTerm?.monthly_payroll_cycle_start_date || '' : '', transport: savedTerm?.daily_transport_allowance ?? current.transport ?? 0, overtimeRate: savedTerm?.overtime_rate_per_hour ?? current.overtimeRate ?? '', overtimeStart: savedTerm?.overtime_start_time || current.overtimeStart || '' }))
  }
  const divisor = Number(line?.rules?.monthly_working_day_divisor || 26)
  const derivedDailyValue = values.paymentType === 'monthly' ? monthlyDailyValue(values.salary, divisor) : null
  return <Modal isOpen title={t('common.edit')} onClose={onClose}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); onSave(line, values) }}>
    <p className="font-extrabold">{line.worker.full_name}</p>
    <fieldset className="rounded-xl border-2 border-(--primary) bg-blue-50/40 p-4"><legend className="px-2 text-base font-extrabold">{t('payroll.paymentType')}</legend><div className="grid grid-cols-2 gap-3">{['weekly', 'monthly'].map((paymentType) => <button key={paymentType} type="button" className={values.paymentType === paymentType ? 'btn-primary' : 'btn-secondary'} onClick={() => selectPaymentType(paymentType)}>{t(`payroll.${paymentType}`)}</button>)}</div></fieldset>
    <section className="border-t pt-3"><h3 className="font-bold">{t('attendance.title')}</h3><div className="mt-2 grid gap-2 sm:grid-cols-2">{line.details.map((detail) => { const day = values.attendance?.[detail.date] || {}; const indicator = detail.isHoliday ? t('payroll.companyHoliday') : isSunday(detail.date) ? t('payroll.sunday') : t('payroll.normalWorkday'); return <div key={detail.date} className="rounded border border-(--border) p-2 text-xs"><p className="font-bold">{detail.date} · {indicator}</p><p className="text-(--muted)">{t('payroll.manualOverride')}: {detail.row?.manual_override ? t('payroll.manual') : t('payroll.automatic')} · {t('payroll.candidateOvertimeHours')}: {detail.candidateOvertimeHours || '—'}</p><div className="mt-1 grid grid-cols-3 gap-1"><select className="input-base" disabled={!draft} value={day.status || 'absent'} onChange={(event) => updateAttendance(detail.date, 'status', event.target.value)}><option value="present">{t('attendance.present')}</option><option value="half_day">{t('attendance.halfDay')}</option><option value="absent">{t('attendance.absent')}</option></select><input className="input-base" disabled={!draft} aria-label={t('attendance.checkIn')} type="time" value={String(day.check_in || '').slice(0, 5)} onChange={(event) => updateAttendance(detail.date, 'check_in', event.target.value)} /><input className="input-base" disabled={!draft || day.status === 'absent' || day.status === 'half_day'} aria-label={t('attendance.checkOut')} type="time" value={String(day.check_out || '').slice(0, 5)} onChange={(event) => updateAttendance(detail.date, 'check_out', event.target.value)} /></div></div> })}</div></section>
    <section className="border-t pt-3"><h3 className="font-bold">{t('payroll.sundayWork')}</h3>{(line.sundayPayments || []).length ? <div className="mt-2 space-y-2">{line.sundayPayments.map((payment) => <div className="rounded bg-slate-50 p-2 text-sm" key={payment.id}>{payment.work_date} · {payment.daily_value} × {payment.multiplier} = {payment.amount} {payment.currency_code}</div>)}</div> : <p className="mt-2 text-sm text-(--muted)">—</p>}</section>
    <section className="border-t pt-3">
      <h3 className="font-bold">{t('payroll.settingsTitle')}</h3>
      <div className="mt-2 grid gap-2 sm:grid-cols-2">
        <label>{t('payroll.currency')}<select required className="input-base mt-1" value={values.currency || ''} onChange={(event) => update('currency', event.target.value)}><option value="">—</option><option value="CDF">CDF</option><option value="USD">USD</option></select></label>
        {values.paymentType === 'weekly' ? <label>{t('payroll.dailyRate')}<input required className="input-base mt-1" type="number" min="0" step="0.01" value={values.dailyRate || ''} onChange={(event) => update('dailyRate', event.target.value)} /></label> : <><label>{t('payroll.monthlySalary')}<input required className="input-base mt-1" type="number" min="0" step="0.01" value={values.salary || ''} onChange={(event) => update('salary', event.target.value)} /></label><label>{t('payroll.cycleStart')}<input required className="input-base mt-1" type="date" value={values.cycleStart || ''} onChange={(event) => update('cycleStart', event.target.value)} /></label></>}
        <label>{t('payroll.transport')}<input required className="input-base mt-1" type="number" min="0" step="0.01" value={values.transport ?? ''} onChange={(event) => update('transport', event.target.value)} /></label>
        <label>{t('payroll.overtimeRate')}<input className="input-base mt-1" type="number" min="0" step="0.01" value={values.overtimeRate || ''} onChange={(event) => update('overtimeRate', event.target.value)} /></label>
        <label>{t('payroll.overtimeStart')}<input className="input-base mt-1" type="time" value={values.overtimeStart || ''} onChange={(event) => update('overtimeStart', event.target.value)} /></label>
        <label>{t('payroll.effectiveFrom')}<input required className="input-base mt-1" type="date" value={values.effectiveFrom || ''} onChange={(event) => update('effectiveFrom', event.target.value)} /></label>
      </div>
      {values.paymentType === 'monthly' && derivedDailyValue != null ? <div className="mt-3 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm"><p className="font-bold">{t('payroll.derivedDailyValue')}: {formatPayrollMoney(derivedDailyValue, { currency: values.currency, paymentType: 'monthly' })}</p><p className="mt-1 text-xs text-(--muted)">{t('payroll.derivedDailyValueHelp', { divisor })}</p></div> : null}
    </section>
    <section className="border-t pt-3"><h3 className="font-bold">{t('payroll.adjustments')}</h3>{draft ? <div className="mt-2 grid gap-2 sm:grid-cols-3"><select className="input-base" value={values.type || 'bonus'} onChange={(event) => update('type', event.target.value)}>{['bonus','deduction','advance','transport_correction','overtime_correction','holiday_correction','other'].map((item) => <option key={item} value={item}>{t(`payroll.adjustmentType_${item}`)}</option>)}</select><input className="input-base" type="number" step="0.01" placeholder={t('payroll.amount')} value={values.amount || ''} onChange={(event) => update('amount', event.target.value)} /><input className="input-base" placeholder={t('payroll.reason')} value={values.reason || ''} onChange={(event) => update('reason', event.target.value)} /></div> : <p className="mt-2 text-sm text-amber-800">{t('payroll.adjustmentDraftRequired')}</p>}</section>
    <div className="flex gap-2"><button className="btn-primary" disabled={saving}>{saving ? t('payroll.saving') : t('common.save')}</button><button type="button" className="btn-secondary" onClick={onClose}>{t('common.cancel')}</button></div>
  </form></Modal>
}

export default function MonthlyPayrollOperations() {
  const { t, direction } = useTranslation()
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selectedDue, setSelectedDue] = useState(''); const [editingId, setEditingId] = useState(''); const [saving, setSaving] = useState(false)
  const load = async () => { setLoading(true); try { setData(await getPayrollOperationsDataRequest()); setError('') } catch (requestError) { setError(getErrorMessage(requestError)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const rawLines = useMemo(() => makeLines(data), [data])
  const incompleteWorkers = useMemo(() => (data?.workers || []).filter((worker) => {
    const term = worker.payroll_compensation
    return worker.is_active !== false && worker.payment_type === 'monthly'
      && (term?.monthly_salary == null || !term?.monthly_payroll_cycle_start_date || !term?.currency_code)
  }), [data])
  const groups = useMemo(() => { const map = new Map(); rawLines.forEach((line) => { const key = `${line.cycle.due}|${line.currency}`; map.set(key, { key, due: line.cycle.due, currency: line.currency, lines: [...(map.get(key)?.lines || []), line] }) }); return [...map.values()].map((group) => ({ ...group, totals: totalLines(group.lines) })).sort((a, b) => a.key.localeCompare(b.key)) }, [rawLines])
  const group = groups.find((item) => item.key === selectedDue) || null
  const run = useMemo(() => data?.runs?.find((item) => item.payment_type === 'monthly' && item.scheduled_payment_date === group?.due && item.currency_code === group?.currency) || null, [data, group])
  const linesByWorker = useMemo(() => new Map((data?.payrollLines || []).filter((line) => line.payroll_run_id === run?.id).map((line) => [String(line.worker_id), line])), [data, run])
  const adjustmentsByLine = useMemo(() => { const map = new Map(); (data?.payrollAdjustments || []).forEach((item) => map.set(String(item.payroll_line_id), [...(map.get(String(item.payroll_line_id)) || []), item])); return map }, [data])
  const draftLines = useMemo(() => group?.lines.map((line) => { const stored = linesByWorker.get(String(line.worker.id)); return stored ? applyPayrollAdjustments(line, adjustmentsByLine.get(String(stored.id)) || []) : line }) || [], [adjustmentsByLine, group, linesByWorker])
  const storedLines = useMemo(() => (data?.payrollLines || []).filter((line) => line.payroll_run_id === run?.id).map((line) => { const term = line.compensation_snapshot || {}; const calc = line.calculation_snapshot || {}; return { worker: (data?.workers || []).find((worker) => String(worker.id) === String(line.worker_id)) || { id: line.worker_id, full_name: line.worker_name_snapshot }, term, paymentType: 'monthly', currency: line.currency_code_snapshot || run?.currency_code || null, cycle: { start: line.attendance_period_start, end: line.attendance_period_end, due: line.payment_due_date }, presentDays: Number(line.present_days || 0), halfDays: Number(line.half_days || 0), absentDays: Number(line.absent_days || 0), monthlySalary: Number(term.monthly_salary || 0), dailyValue: Number(calc.daily_value || 0), absenceDeduction: Number(calc.absence_deduction || 0), halfDayDeduction: Number(calc.half_day_deduction || 0), baseAmount: Number(line.base_amount || 0), transportAmount: Number(line.transport_amount || 0), overtimeHours: Number(line.overtime_hours || 0), overtimeAmount: Number(line.overtime_amount || 0), holidayAmount: Number(line.holiday_amount || 0), sundayCarryAmount: Number(calc.sunday_carry_amount || 0), sundayPayments: (data?.sundayPayments || []).filter((payment) => (calc.sunday_payment_ids || []).includes(payment.id)), bonusAmount: Number(line.bonus_amount || 0), deductionAmount: Number(line.deduction_amount || 0), advanceAmount: Number(line.advance_amount || 0), manualAdjustmentAmount: Number(line.manual_adjustment_amount || 0), finalAmount: Number(line.final_amount || 0) } }), [data, run])
  const lines = run && run.status !== 'draft' ? storedLines : draftLines
  const totals = totalLines(lines); const editingLine = lines.find((line) => String(line.worker.id) === String(editingId)) || null; const money = (amount) => formatPayrollMoney(amount, { currency: group?.currency, paymentType: 'monthly' })
  const persist = (source, due, currency) => persistPayrollDraftRequest({ paymentType: 'monthly', dueDate: due, currency, ruleSetId: source.rules.id, lines: makeLines(source).filter((line) => line.cycle.due === due && line.currency === currency) })
  const saveDraft = async () => { if (!group || !data?.rules || (run && run.status !== 'draft')) return; setSaving(true); try { await persist(data, group.due, group.currency); await load() } catch (requestError) { setError(getErrorMessage(requestError)) } finally { setSaving(false) } }
  const changeStatus = async (nextStatus) => { if (!run) return; if (nextStatus === 'reviewed' && (!lines.length || lines.some((line) => line.term?.monthly_salary == null || !line.term?.monthly_payroll_cycle_start_date || !Number.isFinite(Number(line.finalAmount))))) { setError(t('payroll.reviewValidationAmounts')); return } if (nextStatus === 'finalized' && !window.confirm(t('payroll.finalizedConfirmation'))) return; if (nextStatus === 'paid' && !window.confirm(t('payroll.paidConfirmation', { period: group?.due || '', dueDate: group?.due || '', total: money(totals.finalAmount) }))) return; setSaving(true); try { await setWeeklyPayrollRunStatusRequest({ runId: run.id, nextStatus }); await load() } catch (requestError) { setError(getErrorMessage(requestError)) } finally { setSaving(false) } }
  const saveEdit = async (line, values) => { if (values.amount && (!values.reason || !linesByWorker.get(String(line.worker.id)))) { setError(values.reason ? t('payroll.adjustmentDraftRequired') : t('payroll.adjustmentRequired')); return } setSaving(true); try { await saveWorkerPayrollSettingsRequest(line.worker, { payment_type: values.paymentType, currency_code: values.currency, daily_rate: values.dailyRate, monthly_salary: values.salary, daily_transport_allowance: values.transport, overtime_rate_per_hour: values.overtimeRate, overtime_start_time: values.overtimeStart, monthly_payroll_cycle_start_date: values.cycleStart, effective_from: values.effectiveFrom }); if (run?.status === 'draft') await Promise.all(line.details.filter((detail) => { const edit = values.attendance?.[detail.date] || {}; return edit.status !== detail.status || String(edit.check_in || '') !== String(detail.row?.check_in || '').slice(0, 5) || String(edit.check_out || '') !== String(detail.row?.check_out || '').slice(0, 5) }).map((detail) => saveAttendanceManuallyRequest({ row: detail.row || null, workerId: line.worker.id, attendanceDate: detail.date, values: values.attendance[detail.date] }))); const payrollLine = linesByWorker.get(String(line.worker.id)); if (values.amount && payrollLine) await createPayrollAdjustmentRequest({ payrollLineId: payrollLine.id, adjustmentType: values.type, amount: ['bonus','deduction','advance'].includes(values.type) ? Math.abs(Number(values.amount)) : Number(values.amount), reason: values.reason }); const refreshed = await getPayrollOperationsDataRequest(); if (refreshed.runs.find((item) => item.id === run?.id)?.status === 'draft') await persist(refreshed, group.due, group.currency); setEditingId(''); await load() } catch (requestError) { setError(getErrorMessage(requestError)) } finally { setSaving(false) } }
  const columns = [{ key:'worker',header:t('payroll.worker'),render:(line)=>line.worker.full_name},{key:'period',header:t('payroll.attendancePeriod'),render:(line)=>`${line.cycle.start} → ${line.cycle.end}`},{key:'due',header:t('payroll.paymentDueDate'),render:(line)=>line.cycle.due},{key:'present',header:t('payroll.presentDays'),render:(line)=>line.presentDays},{key:'half',header:t('payroll.halfDays'),render:(line)=>line.halfDays},{key:'absent',header:t('payroll.absentDays'),render:(line)=>line.absentDays},{key:'salary',header:t('payroll.monthlySalary'),render:(line)=>money(line.monthlySalary)},{key:'daily',header:t('payroll.dailyValue'),render:(line)=>money(line.dailyValue)},{key:'absence',header:t('payroll.absenceDeduction'),render:(line)=>money(line.absenceDeduction)},{key:'halfDeduction',header:t('payroll.halfDayDeduction'),render:(line)=>money(line.halfDayDeduction)},{key:'overtime',header:t('payroll.candidateOvertimeHours'),render:(line)=>line.overtimeHours||'—'},{key:'transport',header:t('payroll.transport'),render:(line)=>money(line.transportAmount)},{key:'sunday',header:t('payroll.sundayWork'),render:(line)=>money((line.sundayPayments||[]).reduce((sum,payment)=>sum+Number(payment.amount||0),0))},{key:'adjustments',header:t('payroll.adjustments'),render:(line)=>money((line.bonusAmount||0)-(line.deductionAmount||0)-(line.advanceAmount||0)+(line.manualAdjustmentAmount||0))},{key:'final',header:t('payroll.finalPay'),render:(line)=>money(line.finalAmount)},{key:'action',header:t('common.actions'),render:(line)=>(!run||run.status==='draft')?<button className="btn-secondary px-3 py-1" onClick={()=>setEditingId(line.worker.id)}>{t('common.edit')}</button>:null}]
  const groupColumns = [{key:'due',header:t('payroll.paymentDueDate'),render:(item)=>item.due},{key:'currency',header:t('payroll.currency'),render:(item)=>item.currency},{key:'workers',header:t('payroll.workerCount'),render:(item)=>item.lines.length},{key:'total',header:t('payroll.monthlyGroupTotal'),render:(item)=>formatPayrollMoney(item.totals.finalAmount,{currency:item.currency,paymentType:'monthly'})},{key:'open',header:t('common.actions'),render:(item)=><button className="btn-secondary" onClick={()=>setSelectedDue(item.key)}>{t('payroll.open')}</button>}]
  const exportGroup = (kind) => { if (!group) return; const config={ title:t('payroll.monthlyOperations'), metadata:[`${t('common.status')}: ${statusLabel(run?.status||'draft',t)}`,`${t('payroll.paymentDueDate')}: ${group.due}`,`${t('payroll.currency')}: ${group.currency}`], headers:[t('payroll.worker'),t('payroll.attendancePeriod'),t('payroll.presentDays'),t('payroll.halfDays'),t('payroll.absentDays'),t('payroll.monthlySalary'),t('payroll.finalPay')], rows:lines.map((line)=>[line.worker.full_name,`${line.cycle.start} → ${line.cycle.end}`,line.presentDays,line.halfDays,line.absentDays,line.monthlySalary,line.finalAmount]), totals:[[t('payroll.monthlyGroupTotal'),'','','','','',totals.finalAmount]], direction, sheetName:t('payroll.monthly'), filename:`monthly-payroll-${group.due}-${group.currency}` }; if(kind==='print') printPayrollReport(config); else exportPayrollExcel({...config,filename:`${config.filename}.xlsx`}) }
  return <section>{error?<p className="mb-3 rounded bg-red-50 p-3 text-red-700">{error}</p>:null}{incompleteWorkers.length ? <p className="mb-3 rounded bg-amber-50 p-3 text-sm text-amber-800">{t('payroll.needsConfiguration')}: {incompleteWorkers.map((worker) => worker.full_name).join('، ')}</p> : null}{group?<><div className="mb-3 flex flex-wrap items-center gap-2"><button className="btn-secondary" onClick={()=>setSelectedDue('')}>{t('payroll.back')}</button><span className="status-badge status-badge--neutral">{statusLabel(run?.status||'draft',t)}</span>{!run||run.status==='draft'?<><button className="btn-primary" disabled={saving} onClick={saveDraft}>{saving?t('payroll.saving'):t('payroll.saveMonthlyDraft')}</button>{run?<button className="btn-secondary" disabled={saving||!lines.length} onClick={()=>changeStatus('reviewed')}>{t('payroll.submitForReview')}</button>:null}</>:null}{run?.status==='reviewed'?<><button className="btn-secondary" disabled={saving} onClick={()=>changeStatus('draft')}>{t('payroll.returnToDraft')}</button><button className="btn-primary" disabled={saving} onClick={()=>changeStatus('finalized')}>{t('payroll.finalize')}</button></>:null}{run?.status==='finalized'?<button className="btn-primary" disabled={saving} onClick={()=>changeStatus('paid')}>{t('payroll.markPaid')}</button>:null}<button className="btn-secondary" onClick={()=>exportGroup('print')}>{t('reports.print')}</button><button className="btn-secondary" onClick={()=>exportGroup('excel')}>{t('reports.excel')}</button></div><Table columns={columns} data={lines} loading={loading} emptyMessage={t('payroll.noMonthlyConfiguration')} /><div className="mt-3 grid gap-2 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-3"><p>{t('payroll.workerCount')}: {lines.length}</p><p>{t('payroll.monthlySalaryTotal')}: {money(lines.reduce((sum,line)=>sum+Number(line.monthlySalary||0),0))}</p><p className="font-extrabold">{t('payroll.monthlyGroupTotal')}: {money(totals.finalAmount)}</p></div></>:<Table columns={groupColumns} data={groups} loading={loading} emptyMessage={t('payroll.noMonthlyConfiguration')} />}<MonthlyEditPanel line={editingLine} draft={run?.status==='draft'} saving={saving} onClose={()=>setEditingId('')} onSave={saveEdit}/></section>
}
