import { useTranslation } from '../../i18n/LanguageContext'
import { formatPayrollMoney } from '../../utils/payrollCurrency'
import { formatEveningOvertimeMinutes, formatOvertimeMinutes, weeklyPayrollDisplayStatus, weeklyPayrollOvertimeForLine } from '../../utils/weeklyPayrollOvertime'

const dayLabel = (date, language) => new Intl.DateTimeFormat(language === 'ar' ? 'ar' : language === 'fr' ? 'fr-FR' : 'en-US', { weekday: 'short' }).format(new Date(`${date}T12:00:00`))
const statusLabel = (status, t) => ({ present: t('attendance.present'), half_day: t('attendance.halfDay'), absent: t('attendance.absent'), neutral: '—' }[status] || '—')

export default function WeeklyPayrollSheet({ lines, dates, onEdit }) {
  const { t, language } = useTranslation()
  const money = (amount, line) => formatPayrollMoney(amount, { currency: line.currency, paymentType: 'weekly' })
  const workDates = dates.filter((date) => new Date(`${date}T12:00:00Z`).getUTCDay() !== 0)
  return <div className="surface-card overflow-x-auto bg-white" data-weekly-payroll-sheet><table className="w-full table-fixed border-collapse text-sm"><thead><tr><th>{t('payroll.worker')}</th>{workDates.map((date) => <th key={date}>{dayLabel(date, language)}</th>)}<th>{t('payroll.workDayPay')}</th><th>{t('payroll.morningOvertime')}</th><th>{t('payroll.eveningOvertime')}</th><th>{t('payroll.overtimeAmount')}</th><th>{t('payroll.transport')}</th></tr></thead><tbody>{lines.length ? lines.map((line) => { const overtime = weeklyPayrollOvertimeForLine(line); const rateConfigured = line.term?.overtime_rate_per_hour !== '' && line.term?.overtime_rate_per_hour != null; const transportConfigured = line.term?.daily_transport_allowance != null && line.term.daily_transport_allowance !== ''; return <tr key={line.worker.id}><td><button type="button" onClick={() => onEdit(line.worker.id)}>{line.worker.full_name}<span className="block text-xs">{line.worker.employee_code || '—'}</span></button></td>{workDates.map((date) => { const detail = line.details.find((item) => item.date === date); return <td key={date}>{statusLabel(weeklyPayrollDisplayStatus(detail), t)}</td> })}<td dir="ltr">{money(line.attendanceWage, line)}</td><td dir="ltr">{formatOvertimeMinutes(overtime.morningOvertimeMinutes)}</td><td dir="ltr">{formatEveningOvertimeMinutes(overtime.eveningOvertimeMinutes)}</td><td dir="ltr">{rateConfigured && overtime.overtimeMinutes > 0 ? money(line.overtimeAmount, line) : '—'}</td><td dir="ltr">{transportConfigured ? money(line.transportAmount, line) : '—'}</td></tr> }) : <tr><td colSpan={workDates.length + 6}>{t('payroll.noWorkers')}</td></tr>}</tbody></table></div>
}
