import { useTranslation } from '../../i18n/LanguageContext'
import { formatPayrollMoney } from '../../utils/payrollCurrency'
import { formatEveningOvertimeMinutes, formatOvertimeMinutes, weeklyPayrollDisplayStatus, weeklyPayrollOvertimeForLine } from '../../utils/weeklyPayrollOvertime'

const dayLabel = (date, language) => new Intl.DateTimeFormat(language === 'ar' ? 'ar' : language === 'fr' ? 'fr-FR' : 'en-US', { weekday: 'short' }).format(new Date(`${date}T12:00:00`))
const statusLabel = (status, t) => ({ present: t('attendance.present'), half_day: t('attendance.halfDay'), absent: t('attendance.absent'), neutral: '—' }[status] || '—')

export default function WeeklyPayrollSheet({ lines, dates, onEdit }) {
  const { t, language } = useTranslation()
  const money = (amount, line) => formatPayrollMoney(amount, { currency: line.currency, paymentType: 'weekly' })
  const workDates = dates.filter((date) => new Date(`${date}T12:00:00Z`).getUTCDay() !== 0)
  return <div className="surface-card overflow-x-auto bg-white" data-weekly-payroll-sheet><table className="w-full table-fixed border-collapse text-sm"><thead className="bg-slate-50/90"><tr><th className="w-44 px-3 py-2.5 text-start text-xs font-extrabold text-(--muted)">{t('payroll.worker')}</th>{workDates.map((date) => <th key={date} className="w-20 px-1.5 py-2.5 text-center text-xs font-extrabold text-(--muted)">{dayLabel(date, language)}</th>)}<th className="w-28 px-2 py-2.5 text-center text-xs font-extrabold text-(--muted)">{t('payroll.workDayPay')}</th><th className="w-24 px-2 py-2.5 text-center text-xs font-extrabold text-(--muted)">{t('payroll.morningOvertime')}</th><th className="w-24 px-2 py-2.5 text-center text-xs font-extrabold text-(--muted)">{t('payroll.eveningOvertime')}</th><th className="w-28 px-2 py-2.5 text-center text-xs font-extrabold text-(--muted)">{t('payroll.overtimeAmount')}</th><th className="w-28 px-2 py-2.5 text-center text-xs font-extrabold text-(--muted)">{t('payroll.transport')}</th></tr></thead><tbody>{lines.length ? lines.map((line) => { const overtime = weeklyPayrollOvertimeForLine(line); const rateConfigured = line.term?.overtime_rate_per_hour !== '' && line.term?.overtime_rate_per_hour != null; const transportConfigured = line.term?.daily_transport_allowance != null && line.term.daily_transport_allowance !== ''; return <tr key={line.worker.id} className="border-t border-(--border) hover:bg-slate-50/70"><td className="px-3 py-2.5"><button type="button" className="text-start font-extrabold text-(--primary) hover:underline" onClick={() => onEdit(line.worker.id)}>{line.worker.full_name}<span className="mt-0.5 block text-xs font-medium text-(--muted)">{line.worker.employee_code || '—'}</span></button></td>{workDates.map((date) => { const detail = line.details.find((item) => item.date === date); return <td key={date} className="px-1.5 py-2.5 text-center"><span className="whitespace-nowrap text-xs font-bold">{statusLabel(weeklyPayrollDisplayStatus(detail), t)}</span></td> })}<td className="px-2 py-2.5 text-center font-bold" dir="ltr">{money(line.attendanceWage, line)}</td><td className="px-2 py-2.5 text-center font-bold" dir="ltr">{formatOvertimeMinutes(overtime.morningOvertimeMinutes)}</td><td className="px-2 py-2.5 text-center font-bold" dir="ltr">{formatEveningOvertimeMinutes(overtime.eveningOvertimeMinutes)}</td><td className="px-2 py-2.5 text-center font-bold" dir="ltr">{rateConfigured && overtime.overtimeMinutes > 0 ? money(line.overtimeAmount, line) : '—'}</td><td className="px-2 py-2.5 text-center" dir="ltr">{transportConfigured ? money(line.transportAmount, line) : '—'}</td></tr> }) : <tr><td colSpan={workDates.length + 6} className="px-4 py-10 text-center text-(--muted)">{t('payroll.noWorkers')}</td></tr>}</tbody></table></div>
}
